# Generated by Django 4.2.6 on 2023-10-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveBigIntegerField(verbose_name='قیمت محصول')),
                ('product_count', models.IntegerField(verbose_name='تعداد محصول')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoes.product')),
            ],
            options={
                'verbose_name': 'Item',
                
            },
        ),
    ]
